server:
  port: 8080
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: secret
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
          ddl-auto: none
        show-sql: true