version: '3.8'
services:
  postgres:
    image: postgres:17.4
    container_name: t1_postgres
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
