server:
  port: 8083
  servlet:
    context-path: /limits

limits:
  max-amount: 10000.00

spring:
    datasource:
        url: jdbc:postgresql://localhost:5431/postgres
        username: postgres
        password: secret
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
          ddl-auto: none
        show-sql: true